name: Android CI/CD to Firebase App Distribution

# Develop 브랜치에 push 또는 PR이 올 때 확인
on:
  push:
    branches: [ "Develop" ]
  pull_request:
    branches: [ "Develop" ]

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    # 깃허브 runner에서 돌아가는 환경은 java 17버전으로 설정
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # 환경변수(GOOGLE_SERVICES_JSON) 값의 내용을 기반으로 `app/google-services.json` 생성
    - name: Create google-services.json
        run: echo "$GOOGLE_SERVICES_JSON" > app/google-services.json

    # (LOCAL_PROPERTIES_CONTENTS)를 기반으로 local.properties 생성
    # 아직 추가할 Key가 없어서 주석 처리
    #- name: Create local.properties
    #    run: echo "$LOCAL_PROPERTIES_CONTENTS" > local.properties
      
    # Build APK Release
    - name: Build release Apk
      run: ./gradlew assembleDebug

    # Build AAB Release
    - name: Build release Bundle
      run: ./gradlew bundleRelease
